### ISSUE TITLE
Permission denied: b'/opt/restic'

### ISSUE THREAD

**Issue by dbrennand** [dbrennand/ansible-role-autorestic#6]
```
TASK [dbrennand.autorestic : Ensure restic install directory exists] *******************************************************************************
fatal: [nuc.net.domain.tld]: FAILED! => {"changed": false, "msg": "There was an issue creating /opt/restic as requested: [Errno 13] Permission denied: b'/opt/restic'", "path": "/opt/restic/bin"}
```

@whysthatso - I think was most likely introduced in #5 because `/opt` is owned by user root.

**Comment by whysthatso** [comment]
hm, yes. i guess the assumption here is that one runs the role with root privileges, which should probably guarded for?

i'm not sure what's the common way to do this in roles, just the normal `become` ritual?

**Comment by dbrennand** [comment]
Hey @whysthatso - Thanks for the fast reply 🙂 

Yes that's exactly my thinking too, I'm just testing a fix in https://github.com/dbrennand/ansible-role-autorestic/tree/fix/%236
