### ISSUE TITLE
make role dry-runable

### ISSUE THREAD

**Issue by whysthatso** [dbrennand/ansible-role-autorestic#8]
currently task "Ensure restic is executable" is stopping the execution of a playbook run when `-C` is given.

not exactly sure how to prevent this, i will try to look into that. there might be more tasks.

**Comment by dbrennand** [comment]
Hey @whysthatso - Interesting, I've not used this role myself with check mode. I think for the task in question we could use the [skipping tasks](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_checkmode.html#skipping-tasks-or-ignoring-errors-in-check-mode) in check mode.

**Comment by dbrennand** [comment]
Hey @whysthatso - Were you trying to run check mode before or after running this role?

**Comment by dbrennand** [comment]
I've included `check` into the molecule test sequence (equivilent of running check mode) and the molecule tests are passing: https://github.com/dbrennand/ansible-role-autorestic/blob/52df4979331d5926c540cad99b2f0673aab2bac8/molecule/absent/molecule.yml#L28

https://github.com/dbrennand/ansible-role-autorestic/actions/runs/9362724849/job/25772021205

**Comment by dbrennand** [comment]
Hi @whysthatso - Please see my previous comment on check mode passing in molecule tests. Let me know if this needs to be re-opened. Thanks 🙂
